SELECT
    RECIBO.SDS_SEQUENCE_ID,
    RECIBO.IDZONA AS ID_ZONA,
    RECIBO.FECHAEMISION AS FECHA_RECIBO,
    CLIENTE.CODNEMONICO AS CODIGO_DE_CLIENTE,
    CLIENTE.RIF AS RIF_CLIENTE,
    CLIENTE.RAZONSOCIAL AS RAZON_SOCIAL_CLIENTE,
    RECIBOPAGO.FECHADOCUMENTO AS FECHA_PAGO,
    INSTRUMENTOPAGO.NOMBRECORTO AS FORMA_PAGO,
    RECIBOPAGO.NUMERODOCUMENTO1 AS NUMERO_REFERENCIA,
    ENTIDADFINANCIERA.NOMBRECORTO AS BANCO,
    CUENTABANCARIAINTERNA.NUMEROCUENTABANCARIA AS NUMERO_CUENTA_BANCARIA,
    RECIBO.OBSERVACIONES,
    RECIBOPAGO.IDMONEDA AS ID_MONEDA,
    CASE
        WHEN RECIBOPAGO.IDMONEDA = 100 THEN 'USD'
        WHEN RECIBOPAGO.IDMONEDA = 205 THEN 'BS'
        ELSE NULL
    END AS MONEDA,
    TRUNCATE(RECIBOPAGO.MONTO, 2) AS MONTO_DOLAR,
    TRUNCATE(RECIBOPAGO.MONTO_OTRAS, 2) AS MONTO_BS,
    RECIBO.IDRECIBO AS NRO_RECIBO,
    ZONAS.NOMBREZONA AS NOMBRE_ZONA,
    RECIBO.USUARIOCREACION AS USUARIO_AFV,
    COLABORADORES.NOMBRE1COLABORADOR AS VENDEDOR,
    CONCAT(
        '[',
        GROUP_CONCAT(
            DISTINCT MOVCOMERCIAL.NROMOVFISCAL
            ORDER BY
                MOVCOMERCIAL.IDMOVCOMERCIAL ASC SEPARATOR ', '
        ),
        ']'
    ) AS FACTURAS
FROM
    RECIBO
    INNER JOIN ZONAS ON RECIBO.IDZONA = ZONAS.IDZONAS
    INNER JOIN CLIENTE ON RECIBO.IDRECEPTORRECIBO = CLIENTE.IDCLIENTE
    INNER JOIN COLABORADORES ON RECIBO.IDCOLABORADOR = COLABORADORES.IDCOLABORADORES
    INNER JOIN RECIBOPAGO ON RECIBO.IDRECIBO = RECIBOPAGO.IDRECIBO
    AND RECIBO.IDZONA = RECIBOPAGO.IDZONA
    INNER JOIN ENTIDADFINANCIERA ON RECIBOPAGO.IDENTIDADFINANCIERA = ENTIDADFINANCIERA.IDENTIDADFINANCIERA
    INNER JOIN INSTRUMENTOPAGO ON RECIBOPAGO.IDINSTRUMENTOPAGO = INSTRUMENTOPAGO.IDINSTRUMENTOPAGO
    INNER JOIN RECIBODETALLE ON RECIBO.IDRECIBO = RECIBODETALLE.IDRECIBO
    AND RECIBO.IDZONA = RECIBODETALLE.IDZONA
    INNER JOIN MOVCOMERCIAL ON RECIBODETALLE.IDMOVCOMERCIAL = MOVCOMERCIAL.IDMOVCOMERCIAL
    INNER JOIN CUENTABANCARIAINTERNA ON ENTIDADFINANCIERA.IDENTIDADFINANCIERA = CUENTABANCARIAINTERNA.IDENTIDADFINANCIERA
WHERE
    RECIBO.IDCONSECUTIVO = 0
    AND RECIBO.IDRECIBO IN ($ recibos)
    AND RECIBO.IDZONA IN($ zonas)
GROUP BY
    RECIBO.IDRECIBO,
    RECIBO.IDZONA